# NetworkManager configuration for Redmi Pad

[main]
plugins=keyfile

[keyfile]
# Hostname
hostname=yunluo-arch

[connectivity]
uri=http://www.archlinux.org/check_network_status.txt
interval=300

[device]
# WiFi scanning
wifi.scan-rand-mac-address=yes
wifi.backend=wpa_supplicant

[logging]
level=INFO
